# Generated by Django 3.2.7 on 2021-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210904_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='facebook',
            field=models.URLField(default='URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='website',
            field=models.URLField(default='URL', max_length=100),
        ),
    ]
