# Generated by Django 3.2.7 on 2021-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_game_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
